# SQL Connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: root # ${MYSQL_USER}
    password: 1379 # ${MYSQL_PASSWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

## Mail configuration
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

# JWT Configuration
jwt:
  key: 76397924423F4528482B4D6251655468576D5A7134743777217A25432A46294A # ${JWT_SECRET_KEY}
  expiration: 86400000 # ${JWT_EXPIRATION_TIME}
