# SQL Connection
spring:
  datasource:
    url: ${MYSQL_HOST}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

# Mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  key: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION_TIME}
